version: 2.1

jobs:
  test:
    docker:
      - image: rust:latest
    steps:
      - checkout
      - run: cargo --version
      - run:
          name: Install cargo-tarpaulin
          command: "cargo install cargo-tarpaulin"
      - run:
          name: Run Tests
          command: "cargo tarpaulin -v"

workflows:
  test-only:
    jobs:
      - test
