version: 2.1

jobs:
  test:
    docker:
      - image: rust:latest
    steps:
      - checkout
      - run: cargo --version
      - run:
          name: Run Tests
          command: "cargo test --verbose"

workflows:
  test-only:
    jobs:
      - test
